version: "3.6"
services:
  ms2_user_service_mongodb:
    image: mongo:3.6.15-xenial
    container_name: ms2_user_service_mongodb
    tty: true
    restart: "no"
    ports:
      - "${USER_SERVICE_MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_SERVICE_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_SERVICE_MONGODB_PASSWORD}
  ms2_user_service_api:
    image: ms2_user_service_api
    container_name: ms2_user_service_api
    tty: true
    restart: "no"
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - ${USER_SERVICE_INTERNAL_PORT}:${USER_SERVICE_INTERNAL_PORT}
    volumes:
      # mode modules (not shared)
      - /ms2/services/user-service/node_modules
      # app code (shared)
      - ./services/user-service:/ms2/services/user-service
      # code shared between services
      - ./shared:/ms2/shared
    depends_on:
      - ms2_user_service_mongodb
