# https://hub.docker.com/_/node/
FROM node:10.17.0-alpine

WORKDIR /ms4/services/user-service

# Initially only copy package.json. The intermediate image at
# this point will be cached and used UNTIL package.json changes
COPY package.json .

RUN yarn install

# Default command
CMD ["yarn", "dev"]
